language: python

python:
  - 3.3
  - 3.4
  - 3.5

sudo: false

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install coverage==3.7.1 python-coveralls; fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then python -m coverage run setup.py test; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '3.4' ]]; then python setup.py test; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then coveralls; fi
  
notifications:
    email: false