language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

sudo: false

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then pip install python-coveralls; fi
  - pip install flake8

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then python -m coverage run setup.py test; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '3.5' ]]; then python setup.py test; fi
  - flake8 invoiced

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then coveralls; fi
  
notifications:
    email: false