name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install wheel

      - name: Tests
        run: |
          python setup.py test

      - name: Flake8
        run: |
          pip install flake8
          flake8 invoiced

  code_coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.5'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install wheel python-coveralls coverage

      - name: Tests
        run: |
          python -m coverage run setup.py test

      - name: Upload coverage results to Coveralls
        if: ${{ github.event_name == 'push' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        continue-on-error: true
        run: |
          coveralls
